src/Api/DomainsApi.php
tests/Clients/DomainsApiCheckTest.php

The current check endpoint is broken, it does not return a collection even though the code was built around that ([see docs](https://dm.realtimeregister.com/docs/api/domains/check)).
I have fixed it and updated the tests.

Fix check endpoint

---

src/Api/ContactsApi.php
src/Api/DomainsApi.php
src/Api/NotificationsApi.php
src/Api/ProvidersApi.php
src/Domain/Downtime.php
src/Domain/DowntimeCollection.php
src/Domain/Provider.php
src/Domain/ProviderCollection.php
src/RealtimeRegister.php
tests/Clients/ProvidersApiGetDowntimeTest.php
tests/Clients/ProvidersApiGetTest.php
tests/Clients/ProvidersApiListDowntimesTest.php
tests/Clients/ProvidersApiListTest.php
tests/Domain/DomainCollectionTest.php
tests/Domain/DomainObjectTest.php
tests/Domain/data/downtime_invalid_end_date.php
tests/Domain/data/downtime_invalid_id.php
tests/Domain/data/downtime_invalid_provider.php
tests/Domain/data/downtime_invalid_start_date.php
tests/Domain/data/downtime_valid.php
tests/Domain/data/downtime_valid_only_required.php
tests/Domain/data/provider_invalid_name.php
tests/Domain/data/provider_valid.php
tests/Domain/data/provider_valid_only_required.php
tests/RealtimeRegisterClientTest.php

@FrontEndCoffee Hey! I am creating this PR with the requested changes in https://github.com/sandwave-io/realtimeregister-php/issues/9, but I have a question that maybe makes the PR incomplete. 
When we do filter on lists, for every domain object, the code is using a general approach of sending a param named `$search`. 
I did the same for `Providers` and `Downtimes`, but I saw that `search` is not a valid filter, and we have a list of valid params for every listing. Example: https://dm.realtimeregister.com/docs/api/providers/downtime/list
I thought in adding these filters, but it is not convenient to pass so many parameters to a method. Maybe you have planned another approach for this (or maybe I am missunderstanding something :) )
I hope the question has sense. I wait for yout comments, …

Add providers API

---

src/Domain/DomainDetails.php
tests/Domain/data/domain_details_invalid.php
tests/Domain/data/domain_details_valid.php
tests/Domain/data/domain_details_valid_only_required.php

According to the documentation the status of a name is an array of statuses.
https://dm.realtimeregister.com/docs/api/domains/get#response

Use array for domain status as described in documentation

---

src/Exceptions/BadRequestException.php
src/Exceptions/ForbiddenException.php
src/Exceptions/NotFoundException.php
src/Exceptions/UnauthorizedException.php
src/Support/AuthorizedClient.php
tests/AuthorizedClientTest.php

According to the API spec, specific errors can be expected: https://dm.realtimeregister.com/docs/api/errors
The previously implemented `NotFoundException` will never be thrown according to the spec, however I have kept it in here for backwards compatibility (although it is marked as deprecated).
I also added tests to cover the handling of these exceptions.

Update exception handling to reflect API spec

---

.github/workflows/ci.yml
src/Support/AuthorizedClient.php

The ci didn't fail on php-cs-fixer fixes so it didn't actually check the code styling.

Updated Github actions code checker.

---

composer.json

Could not install the package on a fresh Laravel 8 install.
This is becuase laravel requires dragonmantank/cron-expression which in turn requires webmozart/assert version 1.7.0

Use better version constraint webmozart/assert 

---

.github/workflows/ci.yml
composer.json

PHP 7.2 is currently EOL so let's remove support for it. PHPUnit 9.5 also doesn't support it anymore. PHP7.3 is also no longer under active support. If we create a new major version tag it should be fine.

Added PHP 8.0 support and removed PHP 7.2 & 7.3 support. 

---

phpunit.xml

When running the test suite the following warning was shown:
`Warning:       Your XML configuration validates against a deprecated schema.`
`Suggestion:    Migrate your XML configuration using "--migrate-configuration"!`
This MR is the result of running the suggestion.

Updating phpunit schema

---

src/Domain/Billable.php
src/Domain/Enum/ProcessStatusEnum.php
src/Domain/Enum/ResumeTypeEnum.php
src/Domain/NotificationPoll.php
tests/Domain/data/billable_valid_no_amount.php
tests/Domain/data/notification_poll_invalid_count.php
tests/Domain/data/notification_poll_valid.php
tests/Domain/data/notification_poll_valid_only_required.php
tests/Domain/data/process_valid.php

- Constants in ENUMs should be public
- Billable amount key is not set when it's zero
- Notification count in the response is an integer, see: https://dm.realtimeregister.com/docs/api/notifications/poll

Fix process api

---

src/Api/BrandsApi.php
src/Api/ContactsApi.php
src/Api/DomainsApi.php
src/Api/NotificationsApi.php
src/Api/ProcessesApi.php
src/Api/ProvidersApi.php
tests/Clients/BrandsApiListTemplatesTest.php
tests/Clients/BrandsApiListTest.php
tests/Clients/ContactsApiListCountriesTest.php
tests/Clients/ContactsApiListTest.php
tests/Clients/DomainsApiListTest.php
tests/Clients/NotificationsApiListTest.php
tests/Clients/ProcessesApiListTest.php
tests/Clients/ProvidersApiListDowntimesTest.php
tests/Clients/ProvidersApiListTest.php
tests/Helpers/MockedClientFactory.php

List calls allow you to filter the request:
https://dm.realtimeregister.com/docs/api/listings#filtering
This requires the list methods to allow variable key names. This commit enables these filters. 
Example for filtering 100 processes with an ID greater than 50:
```
$parameters = [
'id:gt' => 50
];
$list = $client->processes->list(100, 0, null, $parameters);
```

Allow filtering parameters in list methods

---

src/Domain/LanguageCode.php
src/Domain/LanguageCodes.php
tests/Clients/TLDsApiInfoTest.php
tests/Domain/DomainObjectTest.php
tests/Domain/LanguageCodesTest.php
tests/Domain/data/language_code_allowed_characters.php
tests/Domain/data/language_code_required.php
tests/Domain/data/language_codes.php
tests/Domain/data/tldinfo_com.json
tests/Domain/data/tldinfo_nl.json

Fixes https://github.com/sandwave-io/realtimeregister-php/issues/53
Language codes now get properly stored on the DomainSyntax model (and don't give an error anymore for .com)
The "LanguageCodes" structure differs somewhat from a Collection. (array: country code => language code) That's why I made a separate structure. 
Also added some API client tests using actual json files instead of manually creating the response as a PHP array. Should be more reliable in testing. (that's why this PR is larger than it seems)

Fix language codes

---

src/Domain/Notification.php
tests/Domain/data/notification_valid_only_required.php

The [API documentation](https://dm.yoursrs-ote.com/docs/api/notifications/get#response) first stated incorrectly that the acknowledged and "read date" property on the notification are required, but that wasn't the case when polling or getting notifications. The documentation has been updated and this MR will make those properties optional on the notification DTO.

Update notification DTO properties to be optional

---

src/Api/CertificatesApi.php
tests/Clients/CertificatesApiReissueCertificateTest.php

Documentation: [RTR SSL reissue](https://dm.realtimeregister.com/docs/api/ssl/reissue)
DCV params can be required depending on the type of SSL that needs to get reissued and it was missing from the reissue function signature.

Add dcv parameter to reissue endpoint

---

src/Api/CertificatesApi.php
tests/AuthorizedClientTest.php
tests/Clients/CertificatesApiReissueCertificateTest.php
tests/Clients/CertificatesApiRenewCertificateTest.php
tests/Clients/CertificatesApiRequestCertificateTest.php
tests/Helpers/MockedClientFactory.php

In #60 I wasn't able to mock the response headers, which is necessary to create good coverage for the tests.
Adds a function that allows you to mock the entire response object instead of only the status code & response body. I kept the `makeSdk` function for backwards compatability.
Also casted X-Process-Id header to an integer, since tests were failing because of the invalid return type.

Mock response object

---

src/Api/CertificatesApi.php
tests/Clients/CertificatesApiReissueCertificateTest.php
tests/Clients/CertificatesApiRenewCertificateTest.php
tests/Clients/CertificatesApiRequestCertificateTest.php

Return the X-Process-Id header from the reissue endpoint since reissueing an SSL certificate also starts a new process at RTR. 
Also updated the return type from a nullable integer to a non-nullable integer, RTR will always attach the X-Process-Id header to their response when the endpoint called creates a new process on their end.
According to their docs: 
> When a requests creates a process a "X-Process-Id" header will be included in the response

Return X-Process-Id from reissue endpoint

---

composer.json
src/Api/CustomersApi.php
tests/Clients/CustomersApiListPricesTest.php

Two small changes: 
- Laravel 9 has psr/log version 3, so I can't install the package by default on laravel
- The Pricelist response has [a prices key](https://dm.realtimeregister.com/docs/api/customers/pricelist) which should be used to parse the collection

Allow installation in laravel 9 and small fix in the pricelist response

---

src/Api/DomainsApi.php
src/Domain/AbstractCollection.php
src/Domain/DomainZone.php
src/Domain/DomainZoneRecord.php
src/Domain/DomainZoneRecordCollection.php
src/Domain/Enum/DomainZoneRecordTypeEnum.php
tests/Clients/DomainsApiZoneTest.php
tests/Clients/DomainsApiZoneUpdateTest.php
tests/Domain/data/domain_zone_details.php

Added support for [zoneinfo](https://dm.realtimeregister.com/docs/api/domains/zoneinfo) and [update](https://dm.realtimeregister.com/docs/api/domains/zoneupdate)
~~There is a bit of clutter in this pull request, since it also includes the changes in #64 (I forked it from that one)~~

Added zone info + zone update calls

---

src/Domain/KeyData.php

The base64 encoded publicKey received from RTR can contain spaces and still be valid. During decoding of base64 whitespace characters are ignored.

Bugfix for spaces in DNSSEC public key

---

src/Domain/Enum/DomainZoneServiceEnum.php
src/Domain/Zone.php
tests/Domain/data/zone_valid.php

Sinds de lancering van de nieuwe PREMIUM DNS service is de API op een aantal punten aangepast.
Deze aanpassingen zorgen ervoor dat foutmelding #72 niet meer naar voren komt

Aanpassingen tbv nieuwe zone setup

---

src/Api/CertificatesApi.php
src/Support/RealtimeRegisterResponse.php
tests/AuthorizedClientTest.php
tests/Clients/CertificatesApiRenewCertificateTest.php
tests/Clients/CertificatesApiRequestCertificateTest.php

Fixes the issue where `X-Process-Id` sometimes was send as lowercase. Now it defaults it to lowercase.
`tests/Clients/CertificatesApiReissueCertificateTest.php` tests the existing `X-Process-Id`.

Headers key insensitive

---

src/Domain/Zone.php

The only way to access the properties is to call `toArray` on the object.
I also made the service read only because this is validated so it should not change on the object.

Make zone properties public

---

src/Domain/IsProxyDomain.php
src/IsProxy.php
src/Support/IsProxyConnection.php
tests/Helpers/MockedIsProxyConnection.php
tests/IsProxyConnectionTest.php

Is Proxy allows us to enable functions for error reasons or premium pricings.
https://dm.realtimeregister.com/docs/api/isproxy
This implementation adds the extras to the IsProxyDomain object and adds the enable function to the IsProxy class

[IsProxy] Add the ability to enable functions that return extra data

---

src/Api/FinancialApi.php
src/Domain/ExchangeRates.php
src/Domain/Transaction.php
src/Domain/TransactionCollection.php
src/RealtimeRegister.php
tests/Clients/FinancialApiExchangeRatesTest.php
tests/Clients/FinancialApiGetTransactionTest.php
tests/Clients/FinancialApiListTransactionsTest.php
tests/Domain/data/exchangerates_valid.php
tests/Domain/data/transaction_valid.php

Implement Financials Api

---

src/Api/DomainsApi.php
src/Domain/Billable.php
src/Domain/DomainQuote.php
src/Domain/Enum/BillableActionEnum.php
src/Domain/Quote.php
tests/Clients/DomainsApiRegisterTest.php
tests/Clients/DomainsApiRenewTest.php
tests/Clients/DomainsApiRestoreTest.php
tests/Clients/DomainsApiTransferTest.php
tests/Clients/DomainsApiUpdateTest.php
tests/Domain/BillableObjectTest.php
tests/Domain/DomainObjectTest.php
tests/Domain/data/domain_registration_quote.php
tests/Domain/data/domain_renew_quote.php
tests/Domain/data/domain_restore_quote.php
tests/Domain/data/domain_transfer_quote.php
tests/Domain/data/domain_update_quote.php

https://dm.realtimeregister.com/docs/api/quotes
Added the quote responses to the domain methods.
Also make use of php enums instead of custom ones.
This could be reverted to use the internal enums but i thinks we should move them all to the new php enums.
Another thing i changed/added is making use of readonly properties and a public constructor.
This way an object in immutable and can safely be created with named arguments.

Add quote response to the appropriate methods

---

src/Api/DnsZonesApi.php
src/Domain/DnsZone.php
src/Domain/DnsZoneCollection.php
src/Domain/Enum/ZoneServiceEnum.php
src/IsProxy.php
src/RealtimeRegister.php
tests/Clients/DnsZonesApiCreateTest.php
tests/Clients/DnsZonesApiDeleteTest.php
tests/Clients/DnsZonesApiGetTest.php
tests/Clients/DnsZonesApiListTest.php
tests/Clients/DnsZonesApiUpdateTest.php
tests/Domain/DnsZoneCollectionTest.php
tests/Domain/data/dnszone_valid_with_records.php
tests/Domain/data/dnszone_valid_without_records.php
tests/Domain/data/dnszonecollection_valid.php

Noticed these were missing since the introduction of the new DNS Zone management API.
I've reused the DomainZoneRecordCollection and KeyDataCollection and added a new ZoneServiceEnum

Added DNS zone management options
